### Create Account
POST http://localhost:8080/accounts    HTTP/1.1
Content-Type: application/json

{
  "owner": "ben",
  "currency": "USD"
}

### Get Account
GET http://localhost:8080/accounts/3  HTTP/1.1
Content-Type: application/json


### List Account
GET http://localhost:8080/accounts/?page_id=1&page_size=6  HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8080/accounts/?page_id=100&page_size=6  HTTP/1.1
Content-Type: application/json
